CREATE OR REPLACE TABLE `airline-delay-platform.airline_data.dim_airport` AS
SELECT * FROM UNNEST([
  STRUCT("PPG" AS airport_code, "Pago Pago International Airport" AS airport_name, "Pago Pago" AS city, "TT" AS state),
  STRUCT("SPN" AS airport_code, "Saipan International Airport" AS airport_name, "Saipan" AS city, "TT" AS state),
  STRUCT("GUM" AS airport_code, "Antonio B. Won Pat International Airport" AS airport_name, "Agana" AS city, "TT" AS state),
  STRUCT("STT" AS airport_code, "Cyril E. King Airport" AS airport_name, "St. Thomas" AS city, "VI" AS state),
  STRUCT("STX" AS airport_code, "Henry E Rohlsen Airport" AS airport_name, "St. Croix Island" AS city, "VI" AS state),
  STRUCT("BQN" AS airport_code, "Rafael Hernandez Airport" AS airport_name, "Aguadilla" AS city, "PR" AS state),
  STRUCT("PSE" AS airport_code, "Mercedita Airport" AS airport_name, "Ponce" AS city, "PR" AS state),
  STRUCT("SJU" AS airport_code, "Luis Munoz Marin International Airport" AS airport_name, "San Juan" AS city, "PR" AS state),
  STRUCT("ITO" AS airport_code, "Hilo International Airport" AS airport_name, "Hilo" AS city, "HI" AS state),
  STRUCT("FSM" AS airport_code, "Fort Smith Regional Airport" AS airport_name, "Fort Smith" AS city, "AR" AS state),
  STRUCT("GFK" AS airport_code, "Grand Forks International Airport" AS airport_name, "Grand Forks" AS city, "ND" AS state),
  STRUCT("PRC" AS airport_code, "Ernest A. Love Field" AS airport_name, "Prescott" AS city, "AZ" AS state),
  STRUCT("TTN" AS airport_code, "Trenton Mercer Airport" AS airport_name, "Trenton" AS city, "NJ" AS state),
  STRUCT("BOS" AS airport_code, "General Edward Lawrence Logan International Airport" AS airport_name, "Boston" AS city, "MA" AS state),
  STRUCT("ENV" AS airport_code, "Wendover Airport" AS airport_name, "Wendover" AS city, "UT" AS state),
  STRUCT("BFM" AS airport_code, "Mobile Downtown Airport" AS airport_name, "Mobile" AS city, "AL" AS state),
  STRUCT("OAK" AS airport_code, "Metropolitan Oakland International Airport" AS airport_name, "Oakland" AS city, "CA" AS state),
  STRUCT("OMA" AS airport_code, "Eppley Airfield" AS airport_name, "Omaha" AS city, "NE" AS state),
  STRUCT("OGG" AS airport_code, "Kahului Airport" AS airport_name, "Kahului" AS city, "HI" AS state),
  STRUCT("ICT" AS airport_code, "Wichita Eisenhower National Airport" AS airport_name, "Wichita" AS city, "KS" AS state),
  STRUCT("MCI" AS airport_code, "Kansas City International Airport" AS airport_name, "Kansas City" AS city, "MO" AS state),
  STRUCT("MSN" AS airport_code, "Dane County Regional Truax Field" AS airport_name, "Madison" AS city, "WI" AS state),
  STRUCT("DLG" AS airport_code, "Dillingham Airport" AS airport_name, "Dillingham" AS city, "AK" AS state),
  STRUCT("PHX" AS airport_code, "Phoenix Sky Harbor International Airport" AS airport_name, "Phoenix" AS city, "AZ" AS state),
  STRUCT("BGR" AS airport_code, "Bangor International Airport" AS airport_name, "Bangor" AS city, "ME" AS state),
  STRUCT("GGG" AS airport_code, "East Texas Regional Airport" AS airport_name, "Longview" AS city, "TX" AS state),
  STRUCT("GEG" AS airport_code, "Spokane International Airport" AS airport_name, "Spokane" AS city, "WA" AS state),
  STRUCT("SFO" AS airport_code, "San Francisco International Airport" AS airport_name, "San Francisco" AS city, "CA" AS state),
  STRUCT("GNV" AS airport_code, "Gainesville Regional Airport" AS airport_name, "Gainesville" AS city, "FL" AS state),
  STRUCT("MEM" AS airport_code, "Memphis International Airport" AS airport_name, "Memphis" AS city, "TN" AS state),
  STRUCT("LAX" AS airport_code, "Los Angeles International Airport" AS airport_name, "Los Angeles" AS city, "CA" AS state),
  STRUCT("CLE" AS airport_code, "Cleveland Hopkins International Airport" AS airport_name, "Cleveland" AS city, "OH" AS state),
  STRUCT("CVG" AS airport_code, "Cincinnati Northern Kentucky International Airport" AS airport_name, "Cincinnati" AS city, "KY" AS state),
  STRUCT("JNU" AS airport_code, "Juneau International Airport" AS airport_name, "Juneau" AS city, "AK" AS state),
  STRUCT("LFT" AS airport_code, "Lafayette Regional Airport" AS airport_name, "Lafayette" AS city, "LA" AS state),
  STRUCT("EWR" AS airport_code, "Newark Liberty International Airport" AS airport_name, "Newark" AS city, "NJ" AS state),
  STRUCT("BOI" AS airport_code, "Boise Air Terminal/Gowen Field" AS airport_name, "Boise" AS city, "ID" AS state),
  STRUCT("GCK" AS airport_code, "Garden City Regional Airport" AS airport_name, "Garden City" AS city, "KS" AS state),
  STRUCT("MOT" AS airport_code, "Minot International Airport" AS airport_name, "Minot" AS city, "ND" AS state),
  STRUCT("DAL" AS airport_code, "Dallas Love Field" AS airport_name, "Dallas" AS city, "TX" AS state),
  STRUCT("HLN" AS airport_code, "Helena Regional Airport" AS airport_name, "Helena" AS city, "MT" AS state),
  STRUCT("LCH" AS airport_code, "Lake Charles Regional Airport" AS airport_name, "Lake Charles" AS city, "LA" AS state),
  STRUCT("KOA" AS airport_code, "Ellison Onizuka Kona International At Keahole Airport" AS airport_name, "Kona" AS city, "HI" AS state),
  STRUCT("MYR" AS airport_code, "Myrtle Beach International Airport" AS airport_name, "Myrtle Beach" AS city, "SC" AS state),
  STRUCT("ACK" AS airport_code, "Nantucket Memorial Airport" AS airport_name, "Nantucket" AS city, "MA" AS state),
  STRUCT("DCA" AS airport_code, "Ronald Reagan Washington National Airport" AS airport_name, "Washington" AS city, "VA" AS state),
  STRUCT("ACY" AS airport_code, "Atlantic City International Airport" AS airport_name, "Atlantic City" AS city, "NJ" AS state),
  STRUCT("PUB" AS airport_code, "Pueblo Memorial Airport" AS airport_name, "Pueblo" AS city, "CO" AS state),
  STRUCT("PQI" AS airport_code, "Northern Maine Regional Airport at Presque Isle" AS airport_name, "Presque Isle" AS city, "ME" AS state),
  STRUCT("ADQ" AS airport_code, "Kodiak Airport" AS airport_name, "Kodiak" AS city, "AK" AS state),
  STRUCT("FLL" AS airport_code, "Fort Lauderdale Hollywood International Airport" AS airport_name, "Fort Lauderdale" AS city, "FL" AS state),
  STRUCT("INL" AS airport_code, "Falls International Airport" AS airport_name, "International Falls" AS city, "MN" AS state),
  STRUCT("SLC" AS airport_code, "Salt Lake City International Airport" AS airport_name, "Salt Lake City" AS city, "UT" AS state),
  STRUCT("MDT" AS airport_code, "Harrisburg International Airport" AS airport_name, "Harrisburg" AS city, "PA" AS state),
  STRUCT("LNK" AS airport_code, "Lincoln Airport" AS airport_name, "Lincoln" AS city, "NE" AS state),
  STRUCT("LAN" AS airport_code, "Capital City Airport" AS airport_name, "Lansing" AS city, "MI" AS state),
  STRUCT("IAH" AS airport_code, "George Bush Intercontinental Houston Airport" AS airport_name, "Houston" AS city, "TX" AS state),
  STRUCT("BFL" AS airport_code, "Meadows Field" AS airport_name, "Bakersfield" AS city, "CA" AS state),
  STRUCT("ELP" AS airport_code, "El Paso International Airport" AS airport_name, "El Paso" AS city, "TX" AS state),
  STRUCT("HRL" AS airport_code, "Valley International Airport" AS airport_name, "Harlingen" AS city, "TX" AS state),
  STRUCT("CAE" AS airport_code, "Columbia Metropolitan Airport" AS airport_name, "Columbia" AS city, "SC" AS state),
  STRUCT("PNS" AS airport_code, "Pensacola Regional Airport" AS airport_name, "Pensacola" AS city, "FL" AS state),
  STRUCT("HOU" AS airport_code, "William P Hobby Airport" AS airport_name, "Houston" AS city, "TX" AS state),
  STRUCT("PIT" AS airport_code, "Pittsburgh International Airport" AS airport_name, "Pittsburgh" AS city, "PA" AS state),
  STRUCT("BRW" AS airport_code, "Wiley Post Will Rogers Memorial Airport" AS airport_name, "Barrow" AS city, "AK" AS state),
  STRUCT("EFD" AS airport_code, "Ellington Airport" AS airport_name, "Houston" AS city, "TX" AS state),
  STRUCT("MIA" AS airport_code, "Miami International Airport" AS airport_name, "Miami" AS city, "FL" AS state),
  STRUCT("SEA" AS airport_code, "Seattle Tacoma International Airport" AS airport_name, "Seattle" AS city, "WA" AS state),
  STRUCT("CHA" AS airport_code, "Lovell Field" AS airport_name, "Chattanooga" AS city, "TN" AS state),
  STRUCT("JAN" AS airport_code, "Jackson-Medgar Wiley Evers International Airport" AS airport_name, "Jackson" AS city, "MS" AS state),
  STRUCT("LGB" AS airport_code, "Long Beach /Daugherty Field/ Airport" AS airport_name, "Long Beach" AS city, "CA" AS state),
  STRUCT("IPT" AS airport_code, "Williamsport Regional Airport" AS airport_name, "Williamsport" AS city, "PA" AS state),
  STRUCT("IND" AS airport_code, "Indianapolis International Airport" AS airport_name, "Indianapolis" AS city, "IN" AS state),
  STRUCT("HPN" AS airport_code, "Westchester County Airport" AS airport_name, "White Plains" AS city, "NY" AS state),
  STRUCT("YUM" AS airport_code, "Yuma MCAS/Yuma International Airport" AS airport_name, "Yuma" AS city, "AZ" AS state),
  STRUCT("DLH" AS airport_code, "Duluth International Airport" AS airport_name, "Duluth" AS city, "MN" AS state),
  STRUCT("BET" AS airport_code, "Bethel Airport" AS airport_name, "Bethel" AS city, "AK" AS state),
  STRUCT("LIH" AS airport_code, "Lihue Airport" AS airport_name, "Lihue" AS city, "HI" AS state),
  STRUCT("RIC" AS airport_code, "Richmond International Airport" AS airport_name, "Richmond" AS city, "VA" AS state),
  STRUCT("SHV" AS airport_code, "Shreveport Regional Airport" AS airport_name, "Shreveport" AS city, "LA" AS state),
  STRUCT("CDV" AS airport_code, "Merle K (Mudhole) Smith Airport" AS airport_name, "Cordova" AS city, "AK" AS state),
  STRUCT("ORF" AS airport_code, "Norfolk International Airport" AS airport_name, "Norfolk" AS city, "VA" AS state),
  STRUCT("BPT" AS airport_code, "Southeast Texas Regional Airport" AS airport_name, "Beaumont" AS city, "TX" AS state),
  STRUCT("SAV" AS airport_code, "Savannah Hilton Head International Airport" AS airport_name, "Savannah" AS city, "GA" AS state),
  STRUCT("OME" AS airport_code, "Nome Airport" AS airport_name, "Nome" AS city, "AK" AS state),
  STRUCT("PIE" AS airport_code, "St Petersburg Clearwater International Airport" AS airport_name, "St. Petersburg" AS city, "FL" AS state),
  STRUCT("SCC" AS airport_code, "Deadhorse Airport" AS airport_name, "Deadhorse" AS city, "AK" AS state),
  STRUCT("SAT" AS airport_code, "San Antonio International Airport" AS airport_name, "San Antonio" AS city, "TX" AS state),
  STRUCT("ROC" AS airport_code, "Greater Rochester International Airport" AS airport_name, "Rochester" AS city, "NY" AS state),
  STRUCT("RDU" AS airport_code, "Raleigh Durham International Airport" AS airport_name, "Raleigh-durham" AS city, "NC" AS state),
  STRUCT("DAY" AS airport_code, "James M Cox Dayton International Airport" AS airport_name, "Dayton" AS city, "OH" AS state),
  STRUCT("IAG" AS airport_code, "Niagara Falls International Airport" AS airport_name, "Niagara Falls" AS city, "NY" AS state),
  STRUCT("PHF" AS airport_code, "Newport News Williamsburg International Airport" AS airport_name, "Newport News" AS city, "VA" AS state),
  STRUCT("TUS" AS airport_code, "Tucson International Airport" AS airport_name, "Tucson" AS city, "AZ" AS state),
  STRUCT("PVD" AS airport_code, "Theodore Francis Green State Airport" AS airport_name, "Providence" AS city, "RI" AS state),
  STRUCT("BUR" AS airport_code, "Bob Hope Airport" AS airport_name, "Burbank" AS city, "CA" AS state),
  STRUCT("DTW" AS airport_code, "Detroit Metropolitan Wayne County Airport" AS airport_name, "Detroit" AS city, "MI" AS state),
  STRUCT("TPA" AS airport_code, "Tampa International Airport" AS airport_name, "Tampa" AS city, "FL" AS state),
  STRUCT("HIB" AS airport_code, "Range Regional Airport" AS airport_name, "Hibbing" AS city, "MN" AS state),
  STRUCT("MAF" AS airport_code, "Midland International Airport" AS airport_name, "Midland" AS city, "TX" AS state),
  STRUCT("GRB" AS airport_code, "Austin Straubel International Airport" AS airport_name, "Green Bay" AS city, "WI" AS state),
  STRUCT("AGS" AS airport_code, "Augusta Regional At Bush Field" AS airport_name, "Bush Field" AS city, "GA" AS state),
  STRUCT("ISN" AS airport_code, "Sloulin Field International Airport" AS airport_name, "Williston" AS city, "ND" AS state),
  STRUCT("LIT" AS airport_code, "Bill & Hillary Clinton National Airport/Adams Field" AS airport_name, "Little Rock" AS city, "AR" AS state),
  STRUCT("SWF" AS airport_code, "Stewart International Airport" AS airport_name, "Newburgh" AS city, "NY" AS state),
  STRUCT("TBN" AS airport_code, "Waynesville-St. Robert Regional Forney field" AS airport_name, "Fort Leonardwood" AS city, "MO" AS state),
  STRUCT("DFW" AS airport_code, "Dallas Fort Worth International Airport" AS airport_name, "Dallas-Fort Worth" AS city, "TX" AS state),
  STRUCT("MLB" AS airport_code, "Melbourne International Airport" AS airport_name, "Melbourne" AS city, "FL" AS state),
  STRUCT("AUS" AS airport_code, "Austin Bergstrom International Airport" AS airport_name, "Austin" AS city, "TX" AS state),
  STRUCT("LCK" AS airport_code, "Rickenbacker International Airport" AS airport_name, "Columbus" AS city, "OH" AS state),
  STRUCT("MQT" AS airport_code, "Sawyer International Airport" AS airport_name, "Gwinn" AS city, "MI" AS state),
  STRUCT("TYS" AS airport_code, "McGhee Tyson Airport" AS airport_name, "Knoxville" AS city, "TN" AS state),
  STRUCT("STL" AS airport_code, "St Louis Lambert International Airport" AS airport_name, "St. Louis" AS city, "MO" AS state),
  STRUCT("SPS" AS airport_code, "Sheppard Air Force Base-Wichita Falls Municipal Airport" AS airport_name, "Wichita Falls" AS city, "TX" AS state),
  STRUCT("ATL" AS airport_code, "Hartsfield Jackson Atlanta International Airport" AS airport_name, "Atlanta" AS city, "GA" AS state),
  STRUCT("GRR" AS airport_code, "Gerald R. Ford International Airport" AS airport_name, "Grand Rapids" AS city, "MI" AS state),
  STRUCT("FAT" AS airport_code, "Fresno Yosemite International Airport" AS airport_name, "Fresno" AS city, "CA" AS state),
  STRUCT("VRB" AS airport_code, "Vero Beach Regional Airport" AS airport_name, "Vero Beach" AS city, "FL" AS state),
  STRUCT("BNA" AS airport_code, "Nashville International Airport" AS airport_name, "Nashville" AS city, "TN" AS state),
  STRUCT("LRD" AS airport_code, "Laredo International Airport" AS airport_name, "Laredo" AS city, "TX" AS state),
  STRUCT("OTZ" AS airport_code, "Ralph Wien Memorial Airport" AS airport_name, "Kotzebue" AS city, "AK" AS state),
  STRUCT("LGA" AS airport_code, "La Guardia Airport" AS airport_name, "New York" AS city, "NY" AS state),
  STRUCT("TLH" AS airport_code, "Tallahassee Regional Airport" AS airport_name, "Tallahassee" AS city, "FL" AS state),
  STRUCT("ACT" AS airport_code, "Waco Regional Airport" AS airport_name, "Waco" AS city, "TX" AS state),
  STRUCT("SJT" AS airport_code, "San Angelo Regional Mathis Field" AS airport_name, "San Angelo" AS city, "TX" AS state),
  STRUCT("BTV" AS airport_code, "Burlington International Airport" AS airport_name, "Burlington" AS city, "VT" AS state),
  STRUCT("JAX" AS airport_code, "Jacksonville International Airport" AS airport_name, "Jacksonville" AS city, "FL" AS state),
  STRUCT("DRO" AS airport_code, "Durango La Plata County Airport" AS airport_name, "Durango" AS city, "CO" AS state),
  STRUCT("IAD" AS airport_code, "Washington Dulles International Airport" AS airport_name, "Washington" AS city, "VA" AS state),
  STRUCT("CLL" AS airport_code, "Easterwood Field" AS airport_name, "College Station" AS city, "TX" AS state),
  STRUCT("MKE" AS airport_code, "General Mitchell International Airport" AS airport_name, "Milwaukee" AS city, "WI" AS state),
  STRUCT("ABI" AS airport_code, "Abilene Regional Airport" AS airport_name, "Abilene" AS city, "TX" AS state),
  STRUCT("COU" AS airport_code, "Columbia Regional Airport" AS airport_name, "Columbia" AS city, "MO" AS state),
  STRUCT("PDX" AS airport_code, "Portland International Airport" AS airport_name, "Portland" AS city, "OR" AS state),
  STRUCT("PBI" AS airport_code, "Palm Beach International Airport" AS airport_name, "West Palm Beach" AS city, "FL" AS state),
  STRUCT("OGS" AS airport_code, "Ogdensburg International Airport" AS airport_name, "Ogdensburg" AS city, "NY" AS state),
  STRUCT("HNL" AS airport_code, "Daniel K Inouye International Airport" AS airport_name, "Honolulu" AS city, "HI" AS state),
  STRUCT("DSM" AS airport_code, "Des Moines International Airport" AS airport_name, "Des Moines" AS city, "IA" AS state),
  STRUCT("EWN" AS airport_code, "Coastal Carolina Regional Airport" AS airport_name, "New Bern" AS city, "NC" AS state),
  STRUCT("SAN" AS airport_code, "San Diego International Airport" AS airport_name, "San Diego" AS city, "CA" AS state),
  STRUCT("MLU" AS airport_code, "Monroe Regional Airport" AS airport_name, "Monroe" AS city, "LA" AS state),
  STRUCT("ONT" AS airport_code, "Ontario International Airport" AS airport_name, "Ontario" AS city, "CA" AS state),
  STRUCT("ROW" AS airport_code, "Roswell International Air Center Airport" AS airport_name, "Roswell" AS city, "NM" AS state),
  STRUCT("BRO" AS airport_code, "Brownsville South Padre Island International Airport" AS airport_name, "Brownsville" AS city, "TX" AS state),
  STRUCT("DHN" AS airport_code, "Dothan Regional Airport" AS airport_name, "Dothan" AS city, "AL" AS state),
  STRUCT("FMN" AS airport_code, "Four Corners Regional Airport" AS airport_name, "Farmington" AS city, "NM" AS state),
  STRUCT("CRP" AS airport_code, "Corpus Christi International Airport" AS airport_name, "Corpus Christi" AS city, "TX" AS state),
  STRUCT("SYR" AS airport_code, "Syracuse Hancock International Airport" AS airport_name, "Syracuse" AS city, "NY" AS state),
  STRUCT("MDW" AS airport_code, "Chicago Midway International Airport" AS airport_name, "Chicago" AS city, "IL" AS state),
  STRUCT("SJC" AS airport_code, "Norman Y. Mineta San Jose International Airport" AS airport_name, "San Jose" AS city, "CA" AS state),
  STRUCT("HOB" AS airport_code, "Lea County Regional Airport" AS airport_name, "Hobbs" AS city, "NM" AS state),
  STRUCT("DEN" AS airport_code, "Denver International Airport" AS airport_name, "Denver" AS city, "CO" AS state),
  STRUCT("PHL" AS airport_code, "Philadelphia International Airport" AS airport_name, "Philadelphia" AS city, "PA" AS state),
  STRUCT("SUX" AS airport_code, "Sioux Gateway Col. Bud Day Field" AS airport_name, "Sioux City" AS city, "IA" AS state),
  STRUCT("CMH" AS airport_code, "John Glenn Columbus International Airport" AS airport_name, "Columbus" AS city, "OH" AS state),
  STRUCT("TXK" AS airport_code, "Texarkana Regional Webb Field" AS airport_name, "Texarkana" AS city, "AR" AS state),
  STRUCT("PBG" AS airport_code, "Plattsburgh International Airport" AS airport_name, "Plattsburgh" AS city, "NY" AS state),
  STRUCT("ANC" AS airport_code, "Ted Stevens Anchorage International Airport" AS airport_name, "Anchorage" AS city, "AK" AS state),
  STRUCT("GRK" AS airport_code, "Robert Gray  Army Air Field Airport" AS airport_name, "Killeen" AS city, "TX" AS state),
  STRUCT("BLI" AS airport_code, "Bellingham International Airport" AS airport_name, "Bellingham" AS city, "WA" AS state),
  STRUCT("MOB" AS airport_code, "Mobile Regional Airport" AS airport_name, "Mobile" AS city, "AL" AS state),
  STRUCT("SAF" AS airport_code, "Santa Fe Municipal Airport" AS airport_name, "Santa Fe" AS city, "NM" AS state),
  STRUCT("BLV" AS airport_code, "Scott AFB/Midamerica Airport" AS airport_name, "Belleville" AS city, "IL" AS state),
  STRUCT("DRT" AS airport_code, "Del Rio International Airport" AS airport_name, "Del Rio" AS city, "TX" AS state),
  STRUCT("RSW" AS airport_code, "Southwest Florida International Airport" AS airport_name, "Fort Myers" AS city, "FL" AS state),
  STRUCT("AKN" AS airport_code, "King Salmon Airport" AS airport_name, "King Salmon" AS city, "AK" AS state),
  STRUCT("JFK" AS airport_code, "John F Kennedy International Airport" AS airport_name, "New York" AS city, "NY" AS state),
  STRUCT("CYS" AS airport_code, "Cheyenne Regional Jerry Olson Field" AS airport_name, "Cheyenne" AS city, "WY" AS state),
  STRUCT("SCK" AS airport_code, "Stockton Metropolitan Airport" AS airport_name, "Stockton" AS city, "CA" AS state),
  STRUCT("CHS" AS airport_code, "Charleston Air Force Base-International Airport" AS airport_name, "Charleston" AS city, "SC" AS state),
  STRUCT("RNO" AS airport_code, "Reno Tahoe International Airport" AS airport_name, "Reno" AS city, "NV" AS state),
  STRUCT("KTN" AS airport_code, "Ketchikan International Airport" AS airport_name, "Ketchikan" AS city, "AK" AS state),
  STRUCT("BHM" AS airport_code, "Birmingham-Shuttlesworth International Airport" AS airport_name, "Birmingham" AS city, "AL" AS state),
  STRUCT("SMF" AS airport_code, "Sacramento International Airport" AS airport_name, "Sacramento" AS city, "CA" AS state),
  STRUCT("COS" AS airport_code, "City of Colorado Springs Municipal Airport" AS airport_name, "Colorado Springs" AS city, "CO" AS state),
  STRUCT("BUF" AS airport_code, "Buffalo Niagara International Airport" AS airport_name, "Buffalo" AS city, "NY" AS state),
  STRUCT("PAE" AS airport_code, "Snohomish County (Paine Field) Airport" AS airport_name, "Everett" AS city, "WA" AS state),
  STRUCT("CDC" AS airport_code, "Cedar City Regional Airport" AS airport_name, "Cedar City" AS city, "UT" AS state),
  STRUCT("BDL" AS airport_code, "Bradley International Airport" AS airport_name, "Windsor Locks" AS city, "CT" AS state),
  STRUCT("MFE" AS airport_code, "Mc Allen Miller International Airport" AS airport_name, "Mcallen" AS city, "TX" AS state),
  STRUCT("LBB" AS airport_code, "Lubbock Preston Smith International Airport" AS airport_name, "Lubbock" AS city, "TX" AS state),
  STRUCT("ORD" AS airport_code, "Chicago O'Hare International Airport" AS airport_name, "Chicago" AS city, "IL" AS state),
  STRUCT("FAI" AS airport_code, "Fairbanks International Airport" AS airport_name, "Fairbanks" AS city, "AK" AS state),
  STRUCT("ART" AS airport_code, "Watertown International Airport" AS airport_name, "Watertown" AS city, "NY" AS state),
  STRUCT("PSP" AS airport_code, "Palm Springs International Airport" AS airport_name, "Palm Springs" AS city, "CA" AS state),
  STRUCT("AMA" AS airport_code, "Rick Husband Amarillo International Airport" AS airport_name, "Amarillo" AS city, "TX" AS state),
  STRUCT("FOD" AS airport_code, "Fort Dodge Regional Airport" AS airport_name, "Fort Dodge" AS city, "IA" AS state),
  STRUCT("ILM" AS airport_code, "Wilmington International Airport" AS airport_name, "Wilmington" AS city, "NC" AS state),
  STRUCT("BTR" AS airport_code, "Baton Rouge Metropolitan Airport" AS airport_name, "Baton Rouge" AS city, "LA" AS state),
  STRUCT("TYR" AS airport_code, "Tyler Pounds Regional Airport" AS airport_name, "Tyler" AS city, "TX" AS state),
  STRUCT("BWI" AS airport_code, "Baltimore/Washington International Thurgood Marshall Airport" AS airport_name, "Baltimore" AS city, "MD" AS state),
  STRUCT("AEX" AS airport_code, "Alexandria International Airport" AS airport_name, "Alexandria" AS city, "LA" AS state),
  STRUCT("CDB" AS airport_code, "Cold Bay Airport" AS airport_name, "Cold Bay" AS city, "AK" AS state),
  STRUCT("TUL" AS airport_code, "Tulsa International Airport" AS airport_name, "Tulsa" AS city, "OK" AS state),
  STRUCT("SIT" AS airport_code, "Sitka Rocky Gutierrez Airport" AS airport_name, "Sitka" AS city, "AK" AS state),
  STRUCT("ISP" AS airport_code, "Long Island Mac Arthur Airport" AS airport_name, "Islip" AS city, "NY" AS state),
  STRUCT("MSP" AS airport_code, "Minneapolis-St Paul International/Wold-Chamberlain Airport" AS airport_name, "Minneapolis" AS city, "MN" AS state),
  STRUCT("ILG" AS airport_code, "New Castle Airport" AS airport_name, "Wilmington" AS city, "DE" AS state),
  STRUCT("MSY" AS airport_code, "Louis Armstrong New Orleans International Airport" AS airport_name, "New Orleans" AS city, "LA" AS state),
  STRUCT("PWM" AS airport_code, "Portland International Jetport Airport" AS airport_name, "Portland" AS city, "ME" AS state),
  STRUCT("OKC" AS airport_code, "Will Rogers World Airport" AS airport_name, "Oklahoma City" AS city, "OK" AS state),
  STRUCT("ALB" AS airport_code, "Albany International Airport" AS airport_name, "Albany" AS city, "NY" AS state),
  STRUCT("SNA" AS airport_code, "John Wayne Airport-Orange County Airport" AS airport_name, "Santa Ana" AS city, "CA" AS state),
  STRUCT("CPR" AS airport_code, "Casper-Natrona County International Airport" AS airport_name, "Casper" AS city, "WY" AS state),
  STRUCT("VPS" AS airport_code, "Destin-Ft Walton Beach Airport" AS airport_name, "Valparaiso" AS city, "FL" AS state),
  STRUCT("EYW" AS airport_code, "Key West International Airport" AS airport_name, "Key West" AS city, "FL" AS state),
  STRUCT("CLT" AS airport_code, "Charlotte Douglas International Airport" AS airport_name, "Charlotte" AS city, "NC" AS state),
  STRUCT("LAS" AS airport_code, "McCarran International Airport" AS airport_name, "Las Vegas" AS city, "NV" AS state),
  STRUCT("MCO" AS airport_code, "Orlando International Airport" AS airport_name, "Orlando" AS city, "FL" AS state),
  STRUCT("FLO" AS airport_code, "Florence Regional Airport" AS airport_name, "Florence" AS city, "SC" AS state),
  STRUCT("GTF" AS airport_code, "Great Falls International Airport" AS airport_name, "Great Falls" AS city, "MT" AS state),
  STRUCT("YNG" AS airport_code, "Youngstown Warren Regional Airport" AS airport_name, "Youngstown" AS city, "OH" AS state),
  STRUCT("PUW" AS airport_code, "Pullman Moscow Regional Airport" AS airport_name, "Pullman" AS city, "WA" AS state),
  STRUCT("LWS" AS airport_code, "Lewiston Nez Perce County Airport" AS airport_name, "Lewiston" AS city, "ID" AS state),
  STRUCT("ELM" AS airport_code, "Elmira Corning Regional Airport" AS airport_name, "Elmira" AS city, "NY" AS state),
  STRUCT("ITH" AS airport_code, "Ithaca Tompkins Regional Airport" AS airport_name, "Ithaca" AS city, "NY" AS state),
  STRUCT("MRY" AS airport_code, "Monterey Peninsula Airport" AS airport_name, "Monterey" AS city, "CA" AS state),
  STRUCT("SBA" AS airport_code, "Santa Barbara Municipal Airport" AS airport_name, "Santa Barbara" AS city, "CA" AS state),
  STRUCT("DAB" AS airport_code, "Daytona Beach International Airport" AS airport_name, "Daytona Beach" AS city, "FL" AS state),
  STRUCT("HVN" AS airport_code, "Tweed New Haven Airport" AS airport_name, "New Haven" AS city, "CT" AS state),
  STRUCT("AVL" AS airport_code, "Asheville Regional Airport" AS airport_name, "Asheville" AS city, "NC" AS state),
  STRUCT("GSO" AS airport_code, "Piedmont Triad International Airport" AS airport_name, "Greensboro" AS city, "NC" AS state),
  STRUCT("FSD" AS airport_code, "Joe Foss Field Airport" AS airport_name, "Sioux Falls" AS city, "SD" AS state),
  STRUCT("MHT" AS airport_code, "Manchester-Boston Regional Airport" AS airport_name, "Manchester NH" AS city, "NH" AS state),
  STRUCT("SDF" AS airport_code, "Louisville International Standiford Field" AS airport_name, "Louisville" AS city, "KY" AS state),
  STRUCT("CHO" AS airport_code, "Charlottesville Albemarle Airport" AS airport_name, "Charlottesville VA" AS city, "VA" AS state),
  STRUCT("ROA" AS airport_code, "Roanoke–Blacksburg Regional Airport" AS airport_name, "Roanoke VA" AS city, "VA" AS state),
  STRUCT("LEX" AS airport_code, "Blue Grass Airport" AS airport_name, "Lexington KY" AS city, "KY" AS state),
  STRUCT("EVV" AS airport_code, "Evansville Regional Airport" AS airport_name, "Evansville" AS city, "IN" AS state),
  STRUCT("ABQ" AS airport_code, "Albuquerque International Sunport" AS airport_name, "Albuquerque" AS city, "NM" AS state),
  STRUCT("BZN" AS airport_code, "Gallatin Field" AS airport_name, "Bozeman" AS city, "MT" AS state),
  STRUCT("BIL" AS airport_code, "Billings Logan International Airport" AS airport_name, "Billings" AS city, "MT" AS state),
  STRUCT("BTM" AS airport_code, "Bert Mooney Airport" AS airport_name, "Butte" AS city, "MT" AS state),
  STRUCT("TVC" AS airport_code, "Cherry Capital Airport" AS airport_name, "Traverse City" AS city, "MI" AS state),
  STRUCT("JAC" AS airport_code, "Jackson Hole Airport" AS airport_name, "Jacksn Hole" AS city, "WY" AS state),
  STRUCT("RFD" AS airport_code, "Chicago Rockford International Airport" AS airport_name, "Rockford" AS city, "IL" AS state),
  STRUCT("GSP" AS airport_code, "Greenville Spartanburg International Airport" AS airport_name, "Greenville" AS city, "SC" AS state),
  STRUCT("BMI" AS airport_code, "Central Illinois Regional Airport at Bloomington-Normal" AS airport_name, "Bloomington" AS city, "IL" AS state),
  STRUCT("GPT" AS airport_code, "Gulfport Biloxi International Airport" AS airport_name, "Gulfport" AS city, "MS" AS state),
  STRUCT("AZO" AS airport_code, "Kalamazoo Battle Creek International Airport" AS airport_name, "Kalamazoo" AS city, "MI" AS state),
  STRUCT("TOL" AS airport_code, "Toledo Express Airport" AS airport_name, "Toledo" AS city, "OH" AS state),
  STRUCT("FWA" AS airport_code, "Fort Wayne International Airport" AS airport_name, "Fort Wayne" AS city, "IN" AS state),
  STRUCT("DEC" AS airport_code, "Decatur Airport" AS airport_name, "Decatur" AS city, "IL" AS state),
  STRUCT("CID" AS airport_code, "The Eastern Iowa Airport" AS airport_name, "Cedar Rapids" AS city, "IA" AS state),
  STRUCT("LSE" AS airport_code, "La Crosse Municipal Airport" AS airport_name, "La Crosse" AS city, "WI" AS state),
  STRUCT("CWA" AS airport_code, "Central Wisconsin Airport" AS airport_name, "Wassau" AS city, "WI" AS state),
  STRUCT("PIA" AS airport_code, "General Wayne A. Downing Peoria International Airport" AS airport_name, "Peoria" AS city, "IL" AS state),
  STRUCT("ATW" AS airport_code, "Appleton International Airport" AS airport_name, "Appleton" AS city, "WI" AS state),
  STRUCT("RST" AS airport_code, "Rochester International Airport" AS airport_name, "Rochester" AS city, "MN" AS state),
  STRUCT("CMI" AS airport_code, "University of Illinois Willard Airport" AS airport_name, "Champaign" AS city, "IL" AS state),
  STRUCT("MHK" AS airport_code, "Manhattan Regional Airport" AS airport_name, "Manhattan" AS city, "KS" AS state),
  STRUCT("GJT" AS airport_code, "Grand Junction Regional Airport" AS airport_name, "Grand Junction" AS city, "CO" AS state),
  STRUCT("SGU" AS airport_code, "St George Municipal Airport" AS airport_name, "Saint George" AS city, "UT" AS state),
  STRUCT("SRQ" AS airport_code, "Sarasota Bradenton International Airport" AS airport_name, "Sarasota" AS city, "FL" AS state),
  STRUCT("MLI" AS airport_code, "Quad City International Airport" AS airport_name, "Moline" AS city, "IL" AS state),
  STRUCT("BIS" AS airport_code, "Bismarck Municipal Airport" AS airport_name, "Bismarck" AS city, "ND" AS state),
  STRUCT("RAP" AS airport_code, "Rapid City Regional Airport" AS airport_name, "Rapid City" AS city, "SD" AS state),
  STRUCT("CLD" AS airport_code, "Mc Clellan-Palomar Airport" AS airport_name, "Carlsbad" AS city, "CA" AS state),
  STRUCT("FNT" AS airport_code, "Bishop International Airport" AS airport_name, "Flint" AS city, "MI" AS state),
  STRUCT("RDD" AS airport_code, "Redding Municipal Airport" AS airport_name, "Redding" AS city, "CA" AS state),
  STRUCT("EUG" AS airport_code, "Mahlon Sweet Field" AS airport_name, "Eugene" AS city, "OR" AS state),
  STRUCT("IDA" AS airport_code, "Idaho Falls Regional Airport" AS airport_name, "Idaho Falls" AS city, "ID" AS state),
  STRUCT("MFR" AS airport_code, "Rogue Valley International Medford Airport" AS airport_name, "Medford" AS city, "OR" AS state),
  STRUCT("RDM" AS airport_code, "Roberts Field" AS airport_name, "Redmond-Bend" AS city, "OR" AS state),
  STRUCT("CAK" AS airport_code, "Akron Canton Regional Airport" AS airport_name, "Akron" AS city, "OH" AS state),
  STRUCT("HSV" AS airport_code, "Huntsville International Carl T Jones Field" AS airport_name, "Huntsville" AS city, "AL" AS state),
  STRUCT("MGM" AS airport_code, "Montgomery Regional (Dannelly Field) Airport" AS airport_name, "MONTGOMERY" AS city, "AL" AS state),
  STRUCT("TRI" AS airport_code, "Tri-Cities Regional TN/VA Airport" AS airport_name, "BRISTOL" AS city, "TN" AS state),
  STRUCT("PAH" AS airport_code, "Barkley Regional Airport" AS airport_name, "PADUCAH" AS city, "KY" AS state),
  STRUCT("FCA" AS airport_code, "Glacier Park International Airport" AS airport_name, "Kalispell" AS city, "MT" AS state),
  STRUCT("MBS" AS airport_code, "MBS International Airport" AS airport_name, "Saginaw" AS city, "MI" AS state),
  STRUCT("BGM" AS airport_code, "Greater Binghamton/Edwin A Link field" AS airport_name, "Binghamton" AS city, "NY" AS state),
  STRUCT("PSG" AS airport_code, "Petersburg James A Johnson Airport" AS airport_name, "Petersburg" AS city, "AK" AS state),
  STRUCT("SFB" AS airport_code, "Orlando Sanford International Airport" AS airport_name, "Sanford" AS city, "FL" AS state),
  STRUCT("JST" AS airport_code, "John Murtha Johnstown Cambria County Airport" AS airport_name, "Johnstown" AS city, "PA" AS state),
  STRUCT("MSO" AS airport_code, "Missoula International Airport" AS airport_name, "Missoula" AS city, "MT" AS state),
  STRUCT("EGE" AS airport_code, "Eagle County Regional Airport" AS airport_name, "Vail" AS city, "CO" AS state),
  STRUCT("CSG" AS airport_code, "Columbus Metropolitan Airport" AS airport_name, "Columbus" AS city, "GA" AS state),
  STRUCT("LAW" AS airport_code, "Lawton Fort Sill Regional Airport" AS airport_name, "Lawton" AS city, "OK" AS state),
  STRUCT("FNL" AS airport_code, "Northern Colorado Regional Airport" AS airport_name, "Fort Collins" AS city, "CO" AS state),
  STRUCT("FLG" AS airport_code, "Flagstaff Pulliam Airport" AS airport_name, "Flagstaff" AS city, "AZ" AS state),
  STRUCT("TWF" AS airport_code, "Joslin Field Magic Valley Regional Airport" AS airport_name, "Twin Falls" AS city, "ID" AS state),
  STRUCT("MVY" AS airport_code, "Martha's Vineyard Airport" AS airport_name, "Vineyard Haven MA" AS city, "MA" AS state),
  STRUCT("STC" AS airport_code, "St Cloud Regional Airport" AS airport_name, "Saint Cloud" AS city, "MN" AS state),
  STRUCT("GTR" AS airport_code, "Golden Triangle Regional Airport" AS airport_name, "Columbus Mississippi" AS city, "MS" AS state),
  STRUCT("ERI" AS airport_code, "Erie International Tom Ridge Field" AS airport_name, "Erie" AS city, "PA" AS state),
  STRUCT("HYA" AS airport_code, "Barnstable Municipal Boardman Polando Field" AS airport_name, "Barnstable" AS city, "MA" AS state),
  STRUCT("MGW" AS airport_code, "Morgantown Municipal Walter L. Bill Hart Field" AS airport_name, "Morgantown" AS city, "WV" AS state),
  STRUCT("CRW" AS airport_code, "Yeager Airport" AS airport_name, "Charleston" AS city, "WV" AS state),
  STRUCT("AVP" AS airport_code, "Wilkes Barre Scranton International Airport" AS airport_name, "Scranton" AS city, "PA" AS state),
  STRUCT("BJI" AS airport_code, "Bemidji Regional Airport" AS airport_name, "Bemidji" AS city, "MN" AS state),
  STRUCT("FAR" AS airport_code, "Hector International Airport" AS airport_name, "Fargo" AS city, "ND" AS state),
  STRUCT("GCC" AS airport_code, "Gillette Campbell County Airport" AS airport_name, "Gillette" AS city, "WY" AS state),
  STRUCT("SCE" AS airport_code, "University Park Airport" AS airport_name, "State College Pennsylvania" AS city, "PA" AS state),
  STRUCT("MEI" AS airport_code, "Key Field" AS airport_name, "Meridian" AS city, "MS" AS state),
  STRUCT("SPI" AS airport_code, "Abraham Lincoln Capital Airport" AS airport_name, "Springfield" AS city, "IL" AS state),
  STRUCT("HDN" AS airport_code, "Yampa Valley Airport" AS airport_name, "Hayden" AS city, "CO" AS state),
  STRUCT("LBL" AS airport_code, "Liberal Mid-America Regional Airport" AS airport_name, "Liberal" AS city, "KS" AS state),
  STRUCT("COD" AS airport_code, "Yellowstone Regional Airport" AS airport_name, "Cody" AS city, "WY" AS state),
  STRUCT("SGF" AS airport_code, "Springfield Branson National Airport" AS airport_name, "Springfield" AS city, "MO" AS state),
  STRUCT("JLN" AS airport_code, "Joplin Regional Airport" AS airport_name, "Joplin" AS city, "MO" AS state),
  STRUCT("ABE" AS airport_code, "Lehigh Valley International Airport" AS airport_name, "Allentown" AS city, "PA" AS state),
  STRUCT("XNA" AS airport_code, "Northwest Arkansas Regional Airport" AS airport_name, "Bentonville" AS city, "AR" AS state),
  STRUCT("SBN" AS airport_code, "South Bend Regional Airport" AS airport_name, "South Bend" AS city, "IN" AS state),
  STRUCT("ACV" AS airport_code, "California Redwood Coast-Humboldt County Airport" AS airport_name, "Arcata CA" AS city, "CA" AS state),
  STRUCT("OAJ" AS airport_code, "Albert J Ellis Airport" AS airport_name, "Jacksonville NC" AS city, "NC" AS state),
  STRUCT("DBQ" AS airport_code, "Dubuque Regional Airport" AS airport_name, "Dubuque IA" AS city, "IA" AS state),
  STRUCT("ABR" AS airport_code, "Aberdeen Regional Airport" AS airport_name, "Aberdeen" AS city, "SD" AS state),
  STRUCT("ABY" AS airport_code, "Southwest Georgia Regional Airport" AS airport_name, "Albany" AS city, "GA" AS state),
  STRUCT("ALO" AS airport_code, "Waterloo Regional Airport" AS airport_name, "Waterloo" AS city, "IA" AS state),
  STRUCT("ALW" AS airport_code, "Walla Walla Regional Airport" AS airport_name, "Walla Walla" AS city, "WA" AS state),
  STRUCT("APN" AS airport_code, "Alpena County Regional Airport" AS airport_name, "Alpena" AS city, "MI" AS state),
  STRUCT("ATY" AS airport_code, "Watertown Regional Airport" AS airport_name, "Watertown" AS city, "SD" AS state),
  STRUCT("BFF" AS airport_code, "Western Neb. Rgnl/William B. Heilig Airport" AS airport_name, "Scottsbluff" AS city, "NE" AS state),
  STRUCT("BQK" AS airport_code, "Brunswick Golden Isles Airport" AS airport_name, "Brunswick" AS city, "GA" AS state),
  STRUCT("CEC" AS airport_code, "Jack Mc Namara Field Airport" AS airport_name, "Crescent City" AS city, "CA" AS state),
  STRUCT("CGI" AS airport_code, "Cape Girardeau Regional Airport" AS airport_name, "Cape Girardeau" AS city, "MO" AS state),
  STRUCT("CIU" AS airport_code, "Chippewa County International Airport" AS airport_name, "Sault Ste Marie" AS city, "MI" AS state),
  STRUCT("CKB" AS airport_code, "North Central West Virginia Airport" AS airport_name, "Clarksburg" AS city, "WV" AS state),
  STRUCT("CMX" AS airport_code, "Houghton County Memorial Airport" AS airport_name, "Hancock" AS city, "MI" AS state),
  STRUCT("DDC" AS airport_code, "Dodge City Regional Airport" AS airport_name, "Dodge City" AS city, "KS" AS state),
  STRUCT("EAU" AS airport_code, "Chippewa Valley Regional Airport" AS airport_name, "Eau Claire" AS city, "WI" AS state),
  STRUCT("EKO" AS airport_code, "Elko Regional Airport" AS airport_name, "Elko" AS city, "NV" AS state),
  STRUCT("FAY" AS airport_code, "Fayetteville Regional Grannis Field" AS airport_name, "Fayetteville" AS city, "NC" AS state),
  STRUCT("GRI" AS airport_code, "Central Nebraska Regional Airport" AS airport_name, "Grand Island" AS city, "NE" AS state),
  STRUCT("HTS" AS airport_code, "Tri-State/Milton J. Ferguson Field" AS airport_name, "Huntington" AS city, "WV" AS state),
  STRUCT("JMS" AS airport_code, "Jamestown Regional Airport" AS airport_name, "Jamestown" AS city, "ND" AS state),
  STRUCT("LAR" AS airport_code, "Laramie Regional Airport" AS airport_name, "Laramie" AS city, "WY" AS state),
  STRUCT("LBE" AS airport_code, "Arnold Palmer Regional Airport" AS airport_name, "Latrobe" AS city, "PA" AS state),
  STRUCT("LBF" AS airport_code, "North Platte Regional Airport Lee Bird Field" AS airport_name, "North Platte" AS city, "NE" AS state),
  STRUCT("LYH" AS airport_code, "Lynchburg Regional Preston Glenn Field" AS airport_name, "Lynchburg" AS city, "VA" AS state),
  STRUCT("MKG" AS airport_code, "Muskegon County Airport" AS airport_name, "Muskegon" AS city, "MI" AS state),
  STRUCT("OTH" AS airport_code, "Southwest Oregon Regional Airport" AS airport_name, "North Bend" AS city, "OR" AS state),
  STRUCT("OWB" AS airport_code, "Owensboro Daviess County Airport" AS airport_name, "Owensboro" AS city, "KY" AS state),
  STRUCT("PIB" AS airport_code, "Hattiesburg Laurel Regional Airport" AS airport_name, "Hattiesburg/Laurel" AS city, "MS" AS state),
  STRUCT("PIH" AS airport_code, "Pocatello Regional Airport" AS airport_name, "Pocatello" AS city, "ID" AS state),
  STRUCT("PIR" AS airport_code, "Pierre Regional Airport" AS airport_name, "Pierre" AS city, "SD" AS state),
  STRUCT("PLN" AS airport_code, "Pellston Regional Airport of Emmet County Airport" AS airport_name, "Pellston" AS city, "MI" AS state),
  STRUCT("PSM" AS airport_code, "Portsmouth International at Pease Airport" AS airport_name, "Portsmouth" AS city, "NH" AS state),
  STRUCT("RHI" AS airport_code, "Rhinelander Oneida County Airport" AS airport_name, "Rhinelander" AS city, "WI" AS state),
  STRUCT("RKS" AS airport_code, "Southwest Wyoming Regional Airport" AS airport_name, "Rock Springs" AS city, "WY" AS state),
  STRUCT("SBP" AS airport_code, "San Luis County Regional Airport" AS airport_name, "San Luis Obispo" AS city, "CA" AS state),
  STRUCT("SHR" AS airport_code, "Sheridan County Airport" AS airport_name, "Sheridan" AS city, "WY" AS state),
  STRUCT("SLN" AS airport_code, "Salina Municipal Airport" AS airport_name, "Salina" AS city, "KS" AS state),
  STRUCT("SMX" AS airport_code, "Santa Maria Pub/Capt G Allan Hancock Field" AS airport_name, "Santa Maria" AS city, "CA" AS state),
  STRUCT("UIN" AS airport_code, "Quincy Regional Baldwin Field" AS airport_name, "Quincy" AS city, "IL" AS state),
  STRUCT("VCT" AS airport_code, "Victoria Regional Airport" AS airport_name, "Victoria" AS city, "TX" AS state),
  STRUCT("VLD" AS airport_code, "Valdosta Regional Airport" AS airport_name, "Valdosta" AS city, "GA" AS state),
  STRUCT("YKM" AS airport_code, "Yakima Air Terminal McAllister Field" AS airport_name, "Yakima" AS city, "WA" AS state),
  STRUCT("ADK" AS airport_code, "Adak Airport" AS airport_name, "Adak Island" AS city, "AK" AS state),
  STRUCT("GST" AS airport_code, "Gustavus Airport" AS airport_name, "Gustavus" AS city, "AK" AS state),
  STRUCT("WRG" AS airport_code, "Wrangell Airport" AS airport_name, "Wrangell" AS city, "AK" AS state),
  STRUCT("PSC" AS airport_code, "Tri Cities Airport" AS airport_name, "Pasco" AS city, "WA" AS state),
  STRUCT("ORH" AS airport_code, "Worcester Regional Airport" AS airport_name, "Worcester" AS city, "MA" AS state),
  STRUCT("USA" AS airport_code, "Concord-Padgett Regional Airport" AS airport_name, "Concord" AS city, "NC" AS state),
  STRUCT("SUN" AS airport_code, "Friedman Memorial Airport" AS airport_name, "Hailey" AS city, "ID" AS state),
  STRUCT("MCW" AS airport_code, "Mason City Municipal Airport" AS airport_name, "Mason City" AS city, "IA" AS state),
  STRUCT("AZA" AS airport_code, "Phoenix-Mesa-Gateway Airport" AS airport_name, "Mesa" AS city, "AZ" AS state),
  STRUCT("HGR" AS airport_code, "Hagerstown Regional Richard A Henson Field" AS airport_name, "Hagerstown" AS city, "MD" AS state),
  STRUCT("ESC" AS airport_code, "Delta County Airport" AS airport_name, "Escanaba" AS city, "MI" AS state),
  STRUCT("YAK" AS airport_code, "Yakutat Airport" AS airport_name, "Yakutat" AS city, "AK" AS state),
  STRUCT("IMT" AS airport_code, "Ford Airport" AS airport_name, "Iron Mountain" AS city, "MI" AS state),
  STRUCT("LAF" AS airport_code, "Purdue University Airport" AS airport_name, "Lafayette" AS city, "IN" AS state),
  STRUCT("MTJ" AS airport_code, "Montrose Regional Airport" AS airport_name, "Montrose CO" AS city, "CO" AS state),
  STRUCT("RIW" AS airport_code, "Riverton Regional Airport" AS airport_name, "Riverton WY" AS city, "WY" AS state),
  STRUCT("EAT" AS airport_code, "Pangborn Memorial Airport" AS airport_name, "Wenatchee" AS city, "WA" AS state),
  STRUCT("BRD" AS airport_code, "Brainerd Lakes Regional Airport" AS airport_name, "Brainerd" AS city, "MN" AS state),
  STRUCT("LWB" AS airport_code, "Greenbrier Valley Airport" AS airport_name, "Lewisburg" AS city, "WV" AS state),
  STRUCT("PGV" AS airport_code, "Pitt Greenville Airport" AS airport_name, "Greenville" AS city, "NC" AS state),
  STRUCT("BKG" AS airport_code, "Branson Airport" AS airport_name, "Branson" AS city, "MO" AS state),
  STRUCT("UST" AS airport_code, "Northeast Florida Regional Airport" AS airport_name, "St. Augustine Airport" AS city, "FL" AS state),
  STRUCT("STS" AS airport_code, "Charles M. Schulz Sonoma County Airport" AS airport_name, "Santa Rosa" AS city, "CA" AS state),
  STRUCT("ASE" AS airport_code, "Aspen-Pitkin Co/Sardy Field" AS airport_name, "Aspen" AS city, "CO" AS state),
  STRUCT("HYS" AS airport_code, "Hays Regional Airport" AS airport_name, "Hays" AS city, "KS" AS state),
  STRUCT("GUC" AS airport_code, "Gunnison Crested Butte Regional Airport" AS airport_name, "Gunnison" AS city, "CO" AS state),
  STRUCT("PGD" AS airport_code, "Charlotte County Airport" AS airport_name, "Punta Gorda" AS city, "FL" AS state),
  STRUCT("SHD" AS airport_code, "Shenandoah Valley Regional Airport" AS airport_name, "Weyers Cave" AS city, "VA" AS state),
  STRUCT("DVL" AS airport_code, "Devils Lake Regional Airport" AS airport_name, "Devils Lake" AS city, "ND" AS state),
  STRUCT("DIK" AS airport_code, "Dickinson Theodore Roosevelt Regional Airport" AS airport_name, "Dickinson" AS city, "ND" AS state),
  STRUCT("WYS" AS airport_code, "Yellowstone Airport" AS airport_name, "West Yellowstone" AS city, "MT" AS state),
  STRUCT("ALS" AS airport_code, "San Luis Valley Regional Bergman Field" AS airport_name, "Alamosa" AS city, "CO" AS state),
  STRUCT("CNY" AS airport_code, "Canyonlands Field" AS airport_name, "Moab" AS city, "UT" AS state),
  STRUCT("VEL" AS airport_code, "Vernal Regional Airport" AS airport_name, "Vernal" AS city, "UT" AS state),
  STRUCT("MMH" AS airport_code, "Mammoth Yosemite Airport" AS airport_name, "Mammoth Lakes" AS city, "CA" AS state),
  STRUCT("PVU" AS airport_code, "Provo Municipal Airport" AS airport_name, "Provo" AS city, "UT" AS state),
  STRUCT("ECP" AS airport_code, "Northwest Florida Beaches International Airport" AS airport_name, "Panama City" AS city, "FL" AS state),
  STRUCT("HHH" AS airport_code, "Hilton Head Airport" AS airport_name, "Hilton Head Island" AS city, "SC" AS state),
  STRUCT("GUF" AS airport_code, "Jack Edwards Airport" AS airport_name, "Gulf Shores" AS city, "AL" AS state),
  STRUCT("OGD" AS airport_code, "Ogden Hinckley Airport" AS airport_name, "Ogden" AS city, "UT" AS state),
  STRUCT("SWO" AS airport_code, "Stillwater Regional Airport" AS airport_name, "Stillwater" AS city, "OK" AS state),
  STRUCT("BIH" AS airport_code, "Eastern Sierra Regional Airport" AS airport_name, "Bishop" AS city, "CA" AS state),
  STRUCT("EAR" AS airport_code, "Kearney Regional Airport" AS airport_name, "Kearney" AS city, "NE" AS state),
  STRUCT("IFP" AS airport_code, "Laughlin/Bullhead International Airport" AS airport_name, "Bullhead City" AS city, "AZ" AS state),
  STRUCT("TKI" AS airport_code, "Collin County Regional Airport" AS airport_name, "McKinney" AS city, "AK" AS state),
  STRUCT("XWA" AS airport_code, "Williston Basin International Airport" AS airport_name, "Williston" AS city, "ND" AS state)
]);